#!/usr/bin/env python3
"""
Script to replace "RA2" with "Brent" in Jarod's messages in the Slack channel.
"""

import os
import urllib.request
import urllib.error
import json
import time

# Configuration
CHANNEL_ID = "C0A6ZJ9NH5E"
USER_TOKEN = os.environ["SLACK_USER_TOKEN"]
JAROD_USER_ID = "U09Q359K49Z"

# Messages to edit (timestamp: new_text)
MESSAGES_TO_EDIT = {
    "1767298906.544389": "Brent can you look at those files from Alex and label each trajectory as Level 0 / 1 / 2 using only the task outcome error patter and efficiency signals",
    "1767149728.251439": """Ok Brent —

You'll be doing blind labeling for the pilot annotation round.

You will receive 6 execution trajectories generated by Alex.
Assume:
- The toy task spec in tasks/toy_tasks/deferred_config_validation.md
- The rubric in specs/behaviors/cross_turn_information_retention.md

Your task:
For each trajectory:
- Assign a level: 0, 1, or 2
- Briefly justify your label using only observable outcomes:
  - task success/failure
  - error patterns
  - re-query behavior
  - efficiency signals

Constraints:
- Do NOT infer intent
- Do NOT assume missing context beyond what's in the trajectory
- Do NOT try to guess what Alex intended

Post your labels as:
Trajectory X → Level Y + 1–2 sentence justification.""",
    "1767147476.414019": """Ok Brent —

The retention spec is now frozen.

Your role moving forward:
- Stress-test the toy task design for hidden confounds.
- Check whether task difficulty, verbosity, or instruction-following could explain outcomes.

No new metrics or behaviors.
Focus only on whether the evaluation could be misleading.

Reply in Slack.""",
    "1767287846.279259": "Brent can you also confirm that you understand the git repo",
    "1767316231.404689": "Brent i need you to label the pilot_v0.2 traces from Alex",
    "1767147973.260749": """Ok Brent —

The toy task is now frozen: deferred configuration validation with an intervening distractor.

Your role:
Stress-test the evaluation logic, not the task design.

Specifically:
- Identify what alternative explanations (instruction-following, task ease, verbosity, capability) a reviewer might claim
- Show how the existing controls and falsification logic rule these out
- Frame falsification using equivalence testing / confidence intervals (no fixed thresholds)
- Be explicit about what empirical results would invalidate the retention claim

Do NOT introduce new metrics, behaviors, or tasks.
This is a paper-facing section.

Reply in Slack.""",
}


def edit_message(channel_id, timestamp, text, user_token):
    """Edit a Slack message using the chat.update API."""
    url = "https://slack.com/api/chat.update"
    headers = {
        "Authorization": f"Bearer {user_token}",
        "Content-Type": "application/json",
    }
    payload = {
        "channel": channel_id,
        "ts": timestamp,
        "text": text,
    }
    
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(url, data=data, headers=headers, method='POST')
    
    try:
        with urllib.request.urlopen(req) as response:
            return json.loads(response.read().decode('utf-8'))
    except urllib.error.HTTPError as e:
        return {"ok": False, "error": f"HTTP {e.code}: {e.reason}"}


def main():
    """Main function to edit all messages."""
    print(f"Starting to edit {len(MESSAGES_TO_EDIT)} messages...")
    print()
    
    success_count = 0
    error_count = 0
    
    for timestamp, new_text in MESSAGES_TO_EDIT.items():
        print(f"Editing message {timestamp}...")
        result = edit_message(CHANNEL_ID, timestamp, new_text, USER_TOKEN)
        
        if result.get("ok"):
            print(f"  ✓ Successfully edited message {timestamp}")
            success_count += 1
        else:
            print(f"  ✗ Failed to edit message {timestamp}")
            print(f"    Error: {result.get('error', 'Unknown error')}")
            error_count += 1
        
        # Rate limiting - be nice to the API
        time.sleep(1)
    
    print()
    print("=" * 60)
    print(f"Summary:")
    print(f"  Successfully edited: {success_count}")
    print(f"  Failed: {error_count}")
    print("=" * 60)


if __name__ == "__main__":
    main()

